### ISSUE TITLE
Consider using GraphML instead of YAML

### ISSUE THREAD

**Issue by meatballs** [omni4d/model#1]
http://networkx.readthedocs.io/
https://en.wikipedia.org/wiki/DOT_(graph_description_language)
http://graphml.graphdrawing.org/primer/graphml-primer.html

**Comment by meatballs** [comment]
This would allow us to use tools like http://www.yworks.com/products/yed for viewing and editing our models. The format can also be imported into most graph databases

**Comment by drvinceknight** [comment]
Funnily enough I nearly mentioned networkx when I read this earlier today :)

FWIW it's not the best for visualising data, somewhere in their docs they even say something like: "visualising is hard, we pass that on to other stuff".

**Comment by meatballs** [comment]
yep, it can export out to GraphML - I've looked into using GraphML, but it's XML based and horrible to work with directly.

Networkx looks like I should be able to use a file of simple dictionaries (possibly even my yaml), import it into networkx and spew out GraphML if I want to.

**Comment by meatballs** [comment]
I've used pyyaml before to read yaml and it becomes dictionaries within python. Should be possible to define a human-readable yaml layout that I can parse and process to GraphML for viewing. Nice!

**Comment by drvinceknight** [comment]
That sounds really good. I need to look in to GraphML apparently :)

**Comment by meatballs** [comment]
We could repeat the trick on Axelrod too, if that's usefui.

**Comment by meatballs** [comment]
There is the beginning of a graphml file in here doing the same thing as core.yaml - you can see how unreadable it becomes very quickly!

**Comment by meatballs** [comment]
Not 'instead of' but 'as well as'!!

model.py will import the yaml definition and create a graphml file from it
